version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  uvicorn:
    build: .
    image: next-fibonacci:latest
    restart: always
    ports:
      - "8000:8000"
